builtin_interfaces/Time stamp

string mission_id
string interceptor_id
string target_id

cuas_msgs/TargetTrack target

float32 max_speed
float32 safe_altitude
float32 loiter_altitude

float64 launch_latitude
float64 launch_longitude
float32 launch_altitude

float64 home_latitude
float64 home_longitude
float32 home_altitude

bool allow_terminal_phase
bool allow_auto_return
bool allow_abort_on_lost_target